import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import { initializeApp } from "firebase/app";
import { getAnalytics } from "firebase/analytics";
import { firebaseConfig } from '@/firebase-config';
import { getDoc, getFirestore } from "firebase/firestore";
import { doc, onSnapshot } from "firebase/firestore";
import { useEffect, useState } from 'react';


import { useRouter } from 'next/router'
import { TaskBoard } from '@/interfaces/interfaces';
const inter = Inter({ subsets: ['latin'] })

export default function Home() {

const router = useRouter()

// Initialize Firebase
const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

  const [taskBoardInfo,setTaskBoardInfo] = useState<null|TaskBoard>(null)
  const taskboardId = (router.query.id) as string

  useEffect(()=>{

    if(!taskboardId){
      return
    }

    const unsub = onSnapshot(doc(db, "TaskBoards",taskboardId), (doc) => {
      console.log("Current data: ", doc.data());
      const databaseResult = doc.data() as TaskBoard
      setTaskBoardInfo(databaseResult)
    });
  },[db,taskboardId])
    

  return (
    <>
      <Head>
        <title>Tasks - Taskboad - {taskBoardInfo?.boardName}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1>{taskBoardInfo?.boardName}</h1>
      </main>
    </>
  )
}
