import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import { initializeApp } from "firebase/app";
import { getAnalytics } from "firebase/analytics";
import { getDoc, getFirestore } from "firebase/firestore";
import { doc, onSnapshot } from "firebase/firestore";
import { useEffect, useState } from 'react';
import { getAuth, onAuthStateChanged, signOut } from 'firebase/auth';
import router, { useRouter } from 'next/router';
import { firebaseConfig } from '@/firebase-config';



const inter = Inter({ subsets: ['latin'] })

// Your web app's Firebase configuration
// For Firebase JS SDK v7.20.0 and later, measurementId is optional



export default function Home() {


  // Initialize Firebase
  const app = initializeApp(firebaseConfig);
  const db = getFirestore(app);
  const router = useRouter()

  

  const [dataResult, setData] = useState<string | null>('data')

  useEffect(() => {
    
    //here we check if the user is logged or not
    const auth = getAuth();
    onAuthStateChanged(auth, (user) => {
      if (user) {
        // User is signed in, see docs for a list of available properties
        // https://firebase.google.com/docs/reference/js/auth.user
        const uid = user.uid;
        console.log(user)
        setData(user.email)
        
        // ...
      } else {
        // User is signed out
        router.push('/')
      }
    });

  }, [router])


  const userSignOut = () =>{
    const auth = getAuth();
    signOut(auth).then(() => {
      // Sign-out successful.
    }).catch((error) => {
      // An error happened.
    });
  }


  return (
    <>
      <Head>
        <title>Tasks</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1>Dashboard</h1>
        <p>{JSON.stringify(dataResult)}</p>
        <button onClick={userSignOut}>Sign Out</button>
      </main>
    </>
  )
}
